/** @type {import('tailwindcss').Config} */
const defaultTheme = require("tailwindcss/defaultTheme");
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  darkMode: ["class", ".dark-mode"],
  theme: {
    screens: {
      xxs: "375px",
      xs: "475px",
      ...defaultTheme.screens,
    },
    extend: {
      fontFamily: {
        sans: ["Outfit", ...defaultTheme.fontFamily.sans],
      },
      colors: {
        "evening-sea": {
          50: "#ebfef7",
          100: "#cefdea",
          200: "#a1f9da",
          300: "#64f1c7",
          400: "#27e0af",
          500: "#02c79a",
          600: "#00a27e",
          700: "#008268",
          800: "#006653",
          900: "#004f42",
          950: "#003029",
        },
        "paper": {
          DEFAULT: "#EAEEF1",
          dark: "#DEE3E8",
        },
        "ninja": {
          DEFAULT: "#17202A",
          dark: "#161C25",
          light: "#1B1D27"

        },
        'mulberry': {
          '50': '#fcf3f9',
          '100': '#f9eaf5',
          '200': '#f5d5eb',
          '300': '#efb2da',
          '400': '#e482c0',
          '500': '#d75da7',
          '600': '#c43e89',
          '700': '#b43076',
          '800': '#8c285b',
          '900': '#75264f',
          '950': '#47102c',
        },

        'lunar': {
          '50': '#f3f6fb',
          '100': '#e5eaf4',
          '200': '#d1dbec',
          '300': '#b1c3df',
          '400': '#8ba3cf',
          '500': '#6f88c2',
          '600': '#5c70b4',
          '700': '#5160a4',
          '800': '#434c80',
          '900': '#3c456c',
          '950': '#282c43',
        },
      },
      typography: ({ theme }) => ({
        polo: {
          css: {
            '--tw-prose-body': theme('colors.zinc[700]'),
            '--tw-prose-headings': theme('colors.evening-sea[900]'),
            '--tw-prose-lead': theme('colors.zinc[700]'),
            '--tw-prose-links': theme('colors.lunar[700]'),
            '--tw-prose-bold': theme('colors.mulberry[700]'),
            '--tw-prose-counters': theme('colors.mulberry[600]'),
            '--tw-prose-bullets': theme('colors.mulberry[600]'),
            '--tw-prose-quotes': theme('colors.lunar[800]'),
            '--tw-prose-quote-borders': theme('colors.lunar[500]'),
            '--tw-prose-captions': theme('colors.pink[700]'),
            '--tw-prose-code': theme('colors.mulberry[900]'),
            '--tw-prose-pre-code': theme('colors.evening-sea[100]'),
            '--tw-prose-pre-bg': theme('colors.evening-sea[900]'),
            '--tw-prose-invert-body': theme('colors.zinc[300]'),
            '--tw-prose-invert-headings': theme('colors.evening-sea[200]'),
            '--tw-prose-invert-lead': theme('colors.zinc[300]'),
            '--tw-prose-invert-links': theme('colors.lunar[300]'),
            '--tw-prose-invert-hr': theme('colors.evening-sea[900]'),
            '--tw-prose-invert-bold': theme('colors.mulberry[300]'),
            '--tw-prose-invert-counters': theme('colors.mulberry[300]'),
            '--tw-prose-invert-bullets': theme('colors.mulberry[400]'),
            '--tw-prose-invert-quotes': theme('colors.lunar[300]'),
            '--tw-prose-invert-quote-borders': theme('colors.lunar[400]'),
            '--tw-prose-invert-captions': theme('colors.evening-sea[200]'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.mulberry[300]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.evening-sea[900]'),
            '--tw-prose-invert-td-borders': theme('colors.evening-sea[900]'),
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('tailwind-dracula')(),
  ],
};
